package KieRule;
import com.learning.model.Order;

rule "prime user check"
salience 1
no-loop true
	when
		orderObject : Order(buyerStatus == "prime");
	then
		System.out.println("This is prime");
		update(orderObject)
end;

rule "HDFC"
	when
		orderObject : Order(cardType=="HDFC" && price>10000);
	then
		orderObject.setDiscount(orderObject.getDiscount()+5);
end;

rule "ICICI"
salience 2
	when
		orderObject : Order(cardType=="ICICI" && price>15000);
	then
		System.out.println("This is ICICI");
		orderObject.setDiscount(orderObject.getDiscount()+8);
end;

rule "DBS"
	when
		orderObject : Order(cardType=="DBS" && price>15000);
	then
		orderObject.setDiscount(orderObject.getDiscount()+12);
end;